apiVersion: v1
name: fluent-bit
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
  - fluentd
version: 0.19.20
appVersion: 1.8.13
icon: https://fluentbit.io/assets/img/logo1-default.png
home: https://fluentbit.io/
sources:
  - https://github.com/fluent/fluent-bit/
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update fluent-bit image to 1.8.13."
